generar-ejecutable:
    image: mono:latest

    before_script:
        - nuget restore $PATH_TO_SLN

    script:
        - pwd
        - ls -al
        - msbuild /p:Configuration=Release $PATH_TO_SLN
        - mkdir proyecto        
        - mv $PATH_DIR_TO_CSPROJ/bin/Release/* proyecto
        - ls -al proyecto
    artifacts:
        paths:
          - proyecto
        expire_in: 3 days
    when: manual
